### PR TITLE
feat: Ssm paramater policy fix

### PR DESCRIPTION
**Pull request by aaythapa**
### Issue #, if available

#1112 

### Description of changes

The SSM parameter name can have a leading slash and not have one (as per the [docs](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-su-create.html#sysman-parameter-name-constraints)). Right now the SSMParamaeterReadPolicy doesn't account for names that have a leading slash. The resource arn is `arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${parameterName}` which adds an extra slash if the `${parameterName}` has a leading slash. Can't change the policy directly as that would break compatibility. Added a new policy that customers can use when their parameter name has a leading slash. 

### Checklist

- [x] Adheres to the [development guidelines](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines)
- [x] Add/update [unit tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions) using:
    - [ ] Correct values
    - [ ] Bad/wrong values (None, empty, wrong type, length, etc.)
    - [ ] [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected
- [ ] Do these changes include any template validations?
    - [ ] Did the newly validated properties support intrinsics prior to adding the validations? (If unsure, please review [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) before proceeding).
        - [ ] Does the pull request ensure that intrinsics remain functional with the new validations?

### Examples?

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aaythapa** [comment]
Opened security consultation, waiting for approval

**Comment by aaythapa** [comment]
Got security approval

**Review by hoffa — APPROVED** [review]

**Review by ConnorRobertson — APPROVED** [review]

**Comment by xazhao** [comment]
Can we remove the extra slash if it is invalid?

**Comment by aaythapa** [comment]
> Can we remove the extra slash if it is invalid?

Having a name with a slash and and without a slash are both valid so we need both policies

**Pull request merged**
