### PR TITLE
feat: Add HttpApi Event as new event type for AWS::Serverless::StateMachine

### PR DESCRIPTION
**Pull request by Jacco**
*Issue #1851*

*Description of changes:*
- integration test
- unit test(s)
- added a full role to also support stop and startSync
- added action property to event source (can be start, stop, startSync)
- error added when you try to add stop to EXPRESS state machine
- error added when you try to add startSync to STANDARD state machine
- refactored adding auth to HttpApi from `eventsources/push.py` and `stepfunctions/events.py`
- added TimeoutMillis support

*Description of how you validated changes:*
- used the integration test to verify deployed httpapi
- visually verified that all the integrations were added properly
- exported openapi yaml and checked all is there
- tested if the API responded correctly using Postman

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [ ] Update documentation
- [x] Verify transformed template deploys and application functions as expected

*Examples?*

See integration test that was added

*TODO*
- [x] test with various auth options
- [x] Error, Cause, Input, Name,  TraceHeader parameters for action
- [x] discuss role naming/scope
- [x] discuss Action property
- [x] discuss possibility of cross region integration api (eu-west-1) -> statemachine (us-east-1)
- [x] timeOutMilles is missing
- [x] fix code coverage (get open_api.py) green
- [ ] discuss output parameters

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Jacco** [comment]
Discussion about role naming:
======================

It used to be:

`StateMachineName + EventName + 'Role'`

I changed role naming to:

`ApiName + StateMachineName + 'Role'`

If one StateMachine has more than one events to an API the same role will be reused (it will be generated multiple times, so it is exported only once), instead of a new one for every event. Still with this naming a new Role will be created per API. So I propose a improvement:

I think it would even be better `StateMachineName + 'StartStopRole'`

Then only one role would be created. This role can then also be (re)used for other event sources than API.

@jfuss

**Comment by Jacco** [comment]
Discussion about new "Action" property on EventSource:
=========================================
So I added an "Action" property to the event source. There are three possible values:

- `start` for IntegrationSubtype `StepFunctions-StartExecution`
- `stop` for IntegrationSubtype `StepFunctions-StopExecution`
-  `startSync` for IntegrationSubtype `StepFunctions-StartSyncExecution`

If no "Action" property is specified `start` is assumed.

Maybe it makes sense that for EXPRESS StateMachines the default would be `startSync`?

**Comment by Jacco** [comment]
Discussion extra parameters
====================

Name - for ExecutionName in start & startSync
TraceHeader - for startSync
Input - for start & startSync
Error - for stop
Cause - for stop

To support these parameter I added:

Parameters optional property that is a dict (it is not check but passed to CloudFormation)

**Comment by Jacco** [comment]
Discussion cross region HttpApi -> StateMachine
===================================

By **default** the API integration will assume the specified ARN is in the same region as the API is, but the integrations support calling a StateMachine in a different region.

If you specify the Region parameter (which cannot be specified from the request.header/body/path) the API will look for the specified ARN in the Region specified. This means the region in the ARN should match the Region specified otherwise `com.amazonaws.swf.service.v2.model#StateMachineDoesNotExist` is returned.

I think the way to support this with SAM is as follows:

``` yaml
Resources:
  MyStateMachine:
    Type: AWS::Serverless::StateMachineReference
    Properties:
      Name: MyStateMachine
      Region: us-east-1
      Account: 123454567 # is cross account supported
      Events:
        SyncPost:
          Type: HttpApi
          Properties:
            Path: /sync
            Method: post
            Action: startSync    # static checking if resource is EXPRESS??
```

The integration would then use the StateMachine ARN it can contruct from the StateMachineReference properties and also specify the Region in the integration so the integration looks in the correct region for the StateMachine.

**Comment by Jacco** [comment]
Discussion documentation
===================

Where is the documentation :-)

**Comment by mndeveci** [comment]
Closing this due to inactivity. To reopen this please create an issue first to get it prioritized with the SAM team.

**Pull request closed without merging**
