### PR TITLE
Throw error if DefaultAuthorizer is not a string

### PR DESCRIPTION
**Pull request by Shivakishore14**
*Issue #, if available:*
#1245 

*Description of changes:*
Fix issue #1245 , Validate Default Authorizer to be of type string

*Description of how you validated changes:*
* testcase provided in issue

*Checklist:*

- [ *] Write/update tests
- [ ] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected
- [ ] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Shivakishore14** [comment]
The root cause for travis check to fail seems to come from [parameterized_issue_66](https://github.com/wolever/parameterized/issues/66).
Looking into potential workarounds. Meanwhile if anyone has already run into this issue, Feel free to suggest alternate solutions

**Comment by praneetap** [comment]
@Shivakishore14 checking in, do you need help with fixing the build?

**Comment by Shivakishore14** [comment]
That would be really great @praneetap . Build passes for python 3.6, 3.7 and 3.8 but it fails for python 2.7.

**Comment by Shivakishore14** [comment]
@jfuss please do, apologies for not being able to put time into this.

**Comment by jfuss** [comment]
@Shivakishore14 Looking more into this, we actually patched this in a different update: https://github.com/aws/serverless-application-model/pull/1774. I only noticed after I was trying to get this pr updated. Instead of getting this PR updated, I am going to submit a new one that just adds the API test cases. By looking at the other pr, we only have one for StateMachine. 

Thanks again for spending the time to submit this patch!

**Pull request closed without merging**
