### PR TITLE
feat: add StepFunctionsCallbackPolicy policy template

### PR DESCRIPTION
**Pull request by kshyun28**
### Issue #, if available

#2193 

### Description of changes

Adds a new policy template `StepFunctionsCallbackPolicy` with the necessary permissions for implementing [callback patterns](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token).

> For more context, I've recently implemented callback patterns with my Step Functions workflow. A `Lambda function` calls back with the task token along with `SendTaskSuccess` or `SendTaskFailure`.
>
> I've originally implemented this (Step Functions - Lambda callback pattern) via [SAM Connectors](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/reference-sam-connector.html) (`AWS::Lambda::Function` to `AWS::StepFunctions::StateMachine`), but found the connector policy lacking the necessary permissions for the `SendTaskSuccess` or `SendTaskFailure` callbacks.
>
> With connector policies not working for callback patterns, I opted for defining my own policy, which worked. 
>
> This is a continuation of a previous attempt to provide a policy template for callback patterns ([issue](https://github.com/aws/serverless-application-model/issues/2193) and [PR](https://github.com/aws/serverless-application-model/pull/2194)). I've also corrected the `Resource scope`, which was a requested change that was never resolved in the original PR.

### Description of how you validated changes

I validated the changes by updating the `translator` tests and running `make test` on `Python 3.8.16`. 

Total test coverage  is at `95.73%`.
```
Required test coverage of 95% reached. Total coverage: 95.73%

3961 passed in 267.87s (0:04:27)
```

### Checklist

- [x] Adheres to the [development guidelines](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines)
- [x] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions)
    - [x] Using correct values
    - [ ] Using wrong values
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)

### Examples?

Please reach out in the comments if you want to add an example. Examples will be 
added to `sam init` through [aws/aws-sam-cli-app-templates](https://github.com/aws/aws-sam-cli-app-templates).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by moelasmar — DISMISSED** [review]

**Comment by xazhao** [comment]
Hello @kshyun28 , For new policy template PR, it has to go through security review which will take some time. We won't be able to merge the PR now.

**Comment by kshyun28** [comment]
Hello @xazhao, I understand. 

If there's anything else required from me (or if the team thinks this is not a valid use case), please let me know.

Thank you for reviewing!

**Comment by GavinZZ** [comment]
Hi there, just an update on this pull request. We've created the security review internally. It's pending a couple of tasks at the moment. Once the tasks are complete, we will bring it up the security engineer for a final round of review.

**Comment by GavinZZ** [comment]
Hi @kshyun28, sorry for the long wait! I've some good news to share with you. We've finally gotten security engineer's sign off and I will be merging this PR soon.

**Comment by kshyun28** [comment]
Hello @GavinZZ, I appreciate all the hard work you and the AWS-SAM team did in order to add this feature. 

It's my pleasure making a small contribution to a tool I've used for serverless applications.

**Review by paulhcsun — APPROVED** [review]

**Pull request merged**
