### PR TITLE
Issue 1508 remove check requiring identity to be required if ReauthorizeEvery equals zero

### PR DESCRIPTION
**Pull request by daftster**
Check removed to avoid must specify Identity with at least one of Headers, QueryStrings, StageVariables, or Context. error.  This is allowed to be removed from aws console.

*Issue 1508:*
https://github.com/awslabs/serverless-application-model/issues/1508

*Description of changes:*
- According to https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-lambdarequestauthorizer.html#sam-api-lambdarequestauthorizer-identity identity is optional
- Confirmed that I am able to remove all identities from aws console after API had been deployed using sam cli
- Remove validation of having identity when payload type is REQUEST.

*Description of how you validated changes:*

*Checklist:*

- [X] Write/update tests
- [X] `make pr` passes
- [ ] Update documentation
- [X] Verify transformed template deploys and application functions as expected
- [ ] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by wklingler** [comment]
Is there any plans on letting this in?

**Comment by daftster** [comment]
@javiortizmol , can you re-review and re-approved. I am not sure why travis ci fails for me. I just updated code to trigger build and had reverted it since to the code you had approved. thanks.
image

**Comment by akornato** [comment]
Hey is SAM team alive? This is such a simple fix, why has this been abandoned for 5 months now?

**Comment by moretalk** [comment]
This also applies to IdentitySource which is "required" in SAM but it is not required in API Gateway

**Review by moretalk — APPROVED** [review]

**Comment by daftster** [comment]
i've updated the unit test. hopefully this gets approved and merged.

**Review by moretalk — APPROVED** [review]

**Review by akornato — APPROVED** [review]

**Review by javier-caylent — APPROVED** [review]

**Review by javier-caylent — APPROVED** [review]

**Review by CoshUS — APPROVED** [review]

**Review by mingkun2020 — APPROVED** [review]

**Review by mgrandis — CHANGES_REQUESTED** [review]
Thanks for your contribution @daftster and sorry for the late review.
Looks good to me however it seems you were planning on adding unit tests but I don't see any (Code coverage is decreasing).
I would have expected this file to be updated with the new conditions: 
https://github.com/aws/serverless-application-model/blob/develop/tests/model/test_api.py

**Review by mgrandis — APPROVED** [review]

**Pull request merged**
