### PR TITLE
chore: Do not install “schema_source” to site-packages

### PR DESCRIPTION
**Pull request by musicinmybrain**
### Issue #, if available

None, but see https://github.com/aws/serverless-application-model/pull/2825#issuecomment-1447377242.

### Description of changes

Adds `"schema_source"` and `"schema_source.*"` to the `excludes` for the call to `find_packages` in `setup.py`. Fixes unintentional installation of the new `schema_source` directory into `site-packages` since 1.60.0.

Since `black` now wraps the line anyway, alphabetize the excludes for easier examination.

### Description of how you validated changes

Applied as a downstream patch in Fedora Linux’s [`python-aws-sam-translator` package](https://src.fedoraproject.org/rpms/python-aws-sam-translator), where I originally discovered the prpblem.

### Checklist

- [x] Adheres to the [development guidelines](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines)
- [ ] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions) **N/A**
    - [ ] Using correct values
    - [ ] Using wrong values
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md) **N/A**

### Examples?

**N/A**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by aahung — APPROVED** [review]
Thanks. How did you spot this?

**Review by xazhao — APPROVED** [review]

**Comment by GavinZZ** [comment]
Nice, thanks!

**Review by GavinZZ — APPROVED** [review]

**Review by hoffa — APPROVED** [review]

**Comment by aahung** [comment]
@musicinmybrain does this block samtranslator from going into https://src.fedoraproject.org/rpms/python-aws-sam-translator?

**Comment by musicinmybrain** [comment]
> Thanks. How did you spot this?

I was working on updating the Fedora Linux package to 1.60.0, and when I did a test build, RPM produced an error due to installed-but-unpackaged files and directories (that is, ones not mentioned in the spec file’s `%files` list) under `/usr/lib/python3.11/site-packages/schema_source/`. As an RPM packager, if you don’t glob too broadly, it’s pretty easy to catch unexpected new files like this.

**Comment by musicinmybrain** [comment]
> @musicinmybrain does this block samtranslator from going into https://src.fedoraproject.org/rpms/python-aws-sam-translator?

What do you mean by block samtranslator from going into it?

I plan to apply the PR as a downstream patch until it is present in a future release, which will allow me to update the Fedora package to 1.60.0 and beyond. (At least, I can update it for the upcoming F38 release and development/Rawhide branch; stable Fedora releases usually get stuck on a particular version after a while due to dependency issues.)

Is that what you were asking?

**Comment by musicinmybrain** [comment]
Thanks for following up on this so quickly, by the way.

**Comment by aahung** [comment]
I see, good to know. I am interested in similar check directly in sam-translator GH repo. Thanks for the info and the PR. 

> Is that what you were asking?
yeah, glad it doesn't block that.

**Pull request merged**
