### PR TITLE
fix: Fix two places that could cause uncatched errors

### PR DESCRIPTION
**Pull request by aahung**
### Description of changes

Handle when variable types are not expected.

### Checklist

- [ ] Adheres to the [development guidelines](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines)
- [ ] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions)
    - [ ] Using correct values
    - [x] Using wrong values
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)

### Examples?

Please reach out in the comments if you want to add an example. Examples will be 
added to `sam init` through [aws/aws-sam-cli-app-templates](https://github.com/aws/aws-sam-cli-app-templates).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aahung** [comment]
TODO: add tests

**Review by hoffa — APPROVED** [review]

**Review by acristin — COMMENTED** [review]
Please update the description with some words about what the internal errors were.

**Comment by aahung** [comment]
> Please update the description with some words about what the internal errors were.

@acristin changed to "uncatched errors"

**Review by GavinZZ — APPROVED** [review]

**Review by acristin — APPROVED** [review]

**Comment by aahung** [comment]
@acristin the squash message is still the original title 👁️

**Pull request merged**
