### PR TITLE
feat: add introspection, query & resolver limits properties in appsync graphql api

### PR DESCRIPTION
**Pull request by vaibhav170**
### Description of changes

Adding new fields AppSync has added to CFN.
IntrospectionConfig
ResolverCountLimit
QueryDepthLimit

### Description of how you validated changes
this three are pass through properties, tested output of bin/add_transform_test.py script by deploying it using cloudformation, working as expected

### Checklist

- [x] Adheres to the [development guidelines](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines)
- [x] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions)
    - [x] Using correct values
    - [ ] Using wrong values
- [x] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)

### Examples?

Please reach out in the comments if you want to add an example. Examples will be 
added to `sam init` through [aws/aws-sam-cli-app-templates](https://github.com/aws/aws-sam-cli-app-templates).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by vaibhav170** [comment]
Hi @GavinZZ can you help or give direction on getting this PR reviewed and merged, as we need this attributes support for security compliance

**Review by godwingrs22 — APPROVED** [review]
Thanks @vaibhav170 for the contribution. LGTM

**Review by GavinZZ — CHANGES_REQUESTED** [review]
Changes look good, are you able to add an integration test case for these properties to test the deployability?

**Comment by vaibhav170** [comment]
> Changes look good, are you able to add an integration test case for these properties to test the deployability?

hi @GavinZZ  added integration test for Introspection configuration

**Review by GavinZZ — APPROVED** [review]

**Comment by GavinZZ** [comment]
Thank you for contributing!

**Pull request merged**
