### PR TITLE
Format policy_templates.json

### PR DESCRIPTION
**Pull request by mustafa-sadiq**
### Issue #, if available

None I can find

### Description of changes

The policy_templates.json has many formatting discrepancies. For example 

CloudWatchDescribeAlarmHistoryPolicy has 

```json
"Parameters": {},
``` 

where as others have a empty block with white space
```json
"Parameters": {

      },
```

RekognitionFacesManagementPolicy has not been formated with array object like other Statement objects

```json
"Statement": [{
          "Effect": "Allow",
          "Action": [
            "rekognition:IndexFaces",
            "rekognition:DeleteFaces",
            "rekognition:SearchFaces",
            "rekognition:SearchFacesByImage",
            "rekognition:ListFaces"
          ],
```

### Description of how you validated changes

policy_templates.json is still valid JSON 
```sh
cat samtranslator/policy_templates_data/policy_templates.json | jq .
```

### Checklist

- [ ] Adheres to the [development guidelines](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines)
- [ ] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions)
    - [ ] Using correct values
    - [ ] Using wrong values
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)

### Examples?

Please reach out in the comments if you want to add an example. Examples will be 
added to `sam init` through [aws/aws-sam-cli-app-templates](https://github.com/aws/aws-sam-cli-app-templates).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by aahung — CHANGES_REQUESTED** [review]
Thanks for bringing this up. Can you also add this file to CI check so its format can be enforced? Thanks: 

related code: https://github.com/aws/serverless-application-model/blob/d74a89c94c228d3e26ad8dbeb4b2c97ffa5c1d87/Makefile#L32

**Comment by mustafa-sadiq** [comment]
thank you for the review! added it to Makefile black json-format.py and also formatted it using it

Looks like it was not previously added to it as it formats it with regards to layout as well (e.g. "Version" at the end of the file instead of at the beginning) which not be the behavior we want. I can revert this change if you want.

**Comment by ssenchenko** [comment]
Consistent automated formatting is better than a fancy but manual one. I'd say it stays.

**Review by aahung — APPROVED** [review]
verified with 

```
bin/json-format.py --write samtranslator/policy_templates_data/policy_templates.json
reformatted samtranslator/policy_templates_data/policy_templates.json
1 file(s) scanned.
1 file(s) reformatted.
All done! ✨ 🍰 ✨
(samtranslator37) ~/P/serverless-application-model ❯❯❯ cp samtranslator/policy_templates_data/policy_templates.json policy_templates.bak.json
(samtranslator37) ~/P/serverless-application-model ❯❯❯ git co -- .
(samtranslator37) ~/P/serverless-application-model ❯❯❯ g remote add mustafa-sadiq-icf git@github.com:mustafa-sadiq-icf/serverless-application-model.git
(samtranslator37) ~/P/serverless-application-model ❯❯❯ g fetch mustafa-sadiq-icf
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 21 (delta 12), reused 18 (delta 9), pack-reused 0
Unpacking objects: 100% (21/21), 5.87 KiB | 176.00 KiB/s, done.
From github.com:mustafa-sadiq-icf/serverless-application-model
 * [new branch]        develop                                    -> mustafa-sadiq-icf/develop
 * [new branch]        feat/sam-canary                            -> mustafa-sadiq-icf/feat/sam-canary
 * ....
(samtranslator37) ~/P/serverless-application-model ❯❯❯ g co policy-template/formatting
branch 'policy-template/formatting' set up to track 'mustafa-sadiq-icf/policy-template/formatting' by rebasing.
Switched to a new branch 'policy-template/formatting'
(samtranslator37) ~/P/serverless-application-model ❯❯❯ diff samtranslator/policy_templates_data/policy_templates.json policy_templates.bak.json
(empty)
```

**Review by ssenchenko — APPROVED** [review]

**Pull request merged**
