### PR TITLE
chore: Format and enforce formatting for yaml/json in integration/

### PR DESCRIPTION
**Pull request by aahung**
### Checklist

- [ ] Add/update [unit tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions) using:
    - [ ] Correct values
    - [ ] Bad/wrong values (None, empty, wrong type, length, etc.)
    - [ ] [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected
- [ ] Do these changes include any template validations?
    - [ ] Did the newly validated properties support intrinsics prior to adding the validations? (If unsure, please review [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) before proceeding).
        - [ ] Does the pull request ensure that intrinsics remain functional with the new validations?

### Examples?

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aahung** [comment]
First attempt to run integ tests:

```
$ pytest --no-cov integration/ -n auto
...
=============================================================================================== short test summary info ================================================================================================
FAILED integration/combination/test_api_settings.py::TestApiSettings::test_implicit_api_settings - integration.helpers.deployer.exceptions.exceptions.DeployFailedError: Failed to create/update the stack: sam-integ...
FAILED integration/combination/test_function_with_alias.py::TestFunctionWithAlias::test_function_with_alias_with_intrinsics - AssertionError: Lists differ: ['1', '2'] != ['1']
FAILED integration/combination/test_api_settings.py::TestApiSettings::test_method_settings - integration.helpers.deployer.exceptions.exceptions.DeployFailedError: Failed to create/update the stack: sam-integ-stack...
FAILED integration/single/test_basic_application.py::TestBasicApplication::test_basic_application_sar_location_with_intrinsics - FileNotFoundError: [Errno 2] No such file or directory: '/Users/xinhol/Projects/serv...
FAILED integration/single/test_basic_application.py::TestBasicApplication::test_basic_application_sar_location - FileNotFoundError: [Errno 2] No such file or directory: '/Users/xinhol/Projects/serverless-applicati...
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
ERROR integration/combination/test_function_with_self_managed_kafka.py::TestFunctionWithSelfManagedKafka - AttributeError: 'MarkDecorator' object has no attribute '__qualname__'
================================================================ 5 failed, 159 passed, 7 skipped, 30 warnings, 12 errors, 5 rerun in 2378.80s (0:39:38) ================================================================
```

**Comment by aahung** [comment]
Re-run `integration/combination/test_api_settings.py::TestApiSettings::test_implicit_api_settings` after re-creating the companion stack:

```
[gw0] [100%] PASSED integration/combination/test_api_settings.py::TestApiSettings::test_implicit_api_settings 
```

**Comment by aahung** [comment]
Re-run `integration/combination/test_function_with_alias.py::TestFunctionWithAlias::test_function_with_alias_with_intrinsics`, still failed:

```
____________________________________________________________________________ TestFunctionWithAlias.test_function_with_alias_with_intrinsics ____________________________________________________________________________
[gw0] darwin -- Python 3.7.2 /Users/xinhol/.pyenv/versions/3.7.2/envs/samtranslator37/bin/python3.7

self = <integration.combination.test_function_with_alias.TestFunctionWithAlias testMethod=test_function_with_alias_with_intrinsics>

    def test_function_with_alias_with_intrinsics(self):
        parameters = self.get_default_test_template_parameters()
        self.create_and_verify_stack("combination/function_with_alias_intrinsics", parameters)
        alias_name = "Live"
    
        function_name = self.get_physical_id_by_type("AWS::Lambda::Function")
        version_ids = get_function_versions(function_name, self.client_provider.lambda_client)
        self.assertEqual(["1"], version_ids)
    
        alias = self.get_alias(function_name, alias_name)
        self.assertEqual("1", alias["FunctionVersion"])
    
        # Let's change Key by updating the template parameter, but keep template same
        # This should create a new version and leave existing version intact
        parameters[1]["ParameterValue"] = "code2.zip"
    
        self.update_stack(parameters)
        version_ids = get_function_versions(function_name, self.client_provider.lambda_client)
>       self.assertEqual(["1", "2"], version_ids)
E       AssertionError: Lists differ: ['1', '2'] != ['1']
E       
E       First list contains 1 additional elements.
E       First extra element 1:
E       '2'
E       
E       - ['1', '2']
E       + ['1']
```

**Comment by GavinZZ** [comment]
Closing this PR as it's outdated. For the latest formatting change, see https://github.com/aws/serverless-application-model/pull/2617

**Pull request closed without merging**
