### PR TITLE
chore: update properties in schema with new docs

### PR DESCRIPTION
**Pull request by aaythapa**
### Issue #, if available

N/A

### Description of changes

Updated schema by adding docs for new properties

### Description of how you validated changes

`make schema`

### Checklist

- [x] Adheres to the [development guidelines](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#development-guidelines)
- [ ] Add/update [transform tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions)
    - [ ] Using correct values
    - [ ] Using wrong values
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)

### Examples?

Please reach out in the comments if you want to add an example. Examples will be 
added to `sam init` through [aws/aws-sam-cli-app-templates](https://github.com/aws/aws-sam-cli-app-templates).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aaythapa** [comment]
Note: had to change class name `SourceReference` to `SourceReferenceProperties` since having the same class name causes type errors

**Review by aahung — APPROVED** [review]

**Comment by aahung** [comment]
> Note: had to change class name `SourceReference` to `SourceReferenceProperties` since having the same class name causes type errors. This causes the compatibility check to fail but it shouldn't matter (please let me know if i'm wrong)

https://github.com/aws/serverless-application-model/pull/3027

**Review by GavinZZ — APPROVED** [review]

**Comment by aahung** [comment]
Since "Update branch" feature is gone, you probably need manual local merge to make the check pass after #3027 merged

**Review by hoffa — APPROVED** [review]

**Comment by aahung** [comment]
> Since "Update branch" feature is gone, you probably need manual local merge to make the check pass after #3027 merged

false, it is not gone

**Pull request merged**
