### PR TITLE
feat: adding support for SSM Parameters (string) as Type

### PR DESCRIPTION
**Pull request by LautaroJayat**
*Issue #, if available:*
https://github.com/aws/serverless-application-model/issues/2301

*Description of changes:*
* added new entry on parameters.json > Types > enum
* added one input to test all correct types pass
* added one input and output to test that it will fail if a Parameter is not included in the enum from parameters.json
* updated test_validator_root to include these new cases

*Description of how you validated changes:*
* Added missing tests to validate Parameter types are included in the parameter types enum.

*Checklist:*

- [x] Add/update [unit tests](https://github.com/aws/serverless-application-model/blob/develop/DEVELOPMENT_GUIDE.md#unit-testing-with-multiple-python-versions) using:
    - [x] Correct values
    - [x] Bad/wrong values (None, empty, wrong type, length, etc.)
    - [ ] [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
- [ ] Add/update [integration tests](https://github.com/aws/serverless-application-model/blob/develop/INTEGRATION_TESTS.md)
- [ ] `make pr` passes
- [ ] Update documentation
- [ ] Verify transformed template deploys and application functions as expected
- [ ] Do these changes include any template validations?
    - [ ] Did the newly validated properties support intrinsics prior to adding the validations? (If unsure, please review [Intrinsic Functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) before proceeding).
        - [ ] Does the pull request ensure that intrinsics remain functional with the new validations?

*Examples?*

Please reach out in the comments, if you want to add an example. Examples will be 
added to `sam init` through https://github.com/awslabs/aws-sam-cli-app-templates/

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by hawflau — APPROVED** [review]
Thanks for the PR! LGTM!

**Comment by LautaroJayat** [comment]
If someone could give me some info on what are the actual SSM Parameter Types that SAM support, I would really love to update the PR to include all of them.

**Review by moelasmar — APPROVED** [review]

**Comment by hawflau** [comment]
> If someone could give me some info on what are the actual SSM Parameter Types that SAM support, I would really love to update the PR to include all of them.

That's a good question. In fact, SAM works as a [CloudFormation Macro](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-macros.html#template-macros-author). As the doc suggests, it supplies `templateParameterValues` to SAM. So I think SAM would just receive whatever value (string or list) the SSM parameter resolves to. Here's the list of supported SSM parameter types in CloudFormation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types.

**Comment by LautaroJayat** [comment]
@hawflau,
For what I've read in the source, I understand SAM the same way as you are commenting above.
Nonetheless, I would like to only add the parameters that actually will end up working fine after the cloudformation resources are created. That is why I'm trying to find that list, just to let `sam validate` be consistent with the things that actually work after `sam build` and `sam deploy`.

**Comment by hawflau** [comment]
@LautaroJayat 

Yep, the inaccurate part in my comment was " I think SAM would just receive whatever value (string or list) the SSM parameter resolves to". But that's not the point in this PR. I agree that the parity between `sam validate` and other commands like `sam deploy` should be fixed. 

Just want to confirm - do other supported SSM Parameter types also work in `sam deploy`? If so, I think we can include them in this PR.

**Comment by LautaroJayat** [comment]
@hawflau 
I think we could use this list: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-specific-parameter-types-supported
Is the official documentation, I guess it is up to date.
If you agree, I will update the PR to include all of them.

**Pull request merged**
