### PR TITLE
docs: link to HttpApi from "Event source types"

### PR DESCRIPTION
**Pull request by justinmk3**
*Issue #, if available:*
followup to https://github.com/awslabs/serverless-application-model/pull/1290

*Description of changes:*
Minor fix for missing item in table of contents.

*Description of how you validated changes:*
Manual validation

*Checklist:*

- [ ] Write/update tests
- [x] `make pr` passes
- [x] Update documentation
- [ ] Verify transformed template deploys and application functions as expected

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by justinmk3** [comment]
@mgrandis @awood45 @CoshUS @mingkun2020 is anything blocking this? It's a minor change but is confusing for someone reading the reference. And I don't see where the friction is that has delayed merging it.

**Review by CoshUS — APPROVED** [review]

**Comment by mgrandis** [comment]
Hey @justinmk3, let me take a look at this

**Review by mgrandis — APPROVED** [review]

**Comment by mgrandis** [comment]
It seems there was an error with AppVeyor and we are blocked for now.
Could you please try pushing a new commit to see if it unblocks it?
A minor change, like changing the `logical id` from line 391 to `logical ID`.

**Comment by justinmk3** [comment]
Rebased

**Comment by mgrandis** [comment]
Thanks @justinmk3 !

**Pull request merged**
