### PR TITLE
add SecurityPolicy for api gateway cusom domain

### PR DESCRIPTION
**Pull request by qmg-drettie**
*Issue #1445 

*Description of changes:*
Adds support for SecurityPolicy property for AWS::Serverless::Api custom domains.  
Currently cloudformation will default this to TLS_1_0 which is not compliant against most security frameworks.  Adding this will allow users to set to 'TLS_1_2' without needing to create a separate AWS::ApiGateway::DomainName resource.  
example - 
````yaml
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref ACMCertificateArn
        EndpointConfiguration: REGIONAL
        SecurityPolicy: 'TLS_1_2'
````

*Description of how you validated changes:*
tests added

*Checklist:*

- [x] Write/update tests
- [x] `make pr` passes
- [x] Update documentation
- [x] Verify transformed template deploys and application functions as expected
- [x] Add/update example to `examples/2016-10-31`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Kinnary-Raichura** [comment]
Eagerly waiting for this change to get released.

**Comment by tatebosler** [comment]
+1 - this would be great to see rolled out.

**Comment by timoschilling** [comment]
@keetonian @praneetap Any updates on this?

**Comment by timoschilling** [comment]
`SecurityPolicy` should be allowed in the globals too

**Comment by qmg-drettie** [comment]
@timoschilling [Domain](https://github.com/awslabs/serverless-application-model/blob/58a81c2bdd20a9c19133346f96ab27ea739fd7fb/samtranslator/plugins/globals/globals.py#L65) is already a supported property so no change is required. 

 I've run a test to confirm SecurityPolicy is passed when specified in the Golbals like so -
```
Globals:
  Api:
    Domain:
      CertificateArn: !Ref CertificateArn
      DomainName: !Ref DomainName
      EndpointConfiguration: REGIONAL
      SecurityPolicy: 'TLS_1_2'
```

**Comment by timoschilling** [comment]
Sorry my fault, I have seen SecurityPolicy as a root property and not a property of domain

**Comment by timoschilling** [comment]
@praneetap @sriram-mv any updates on this?

**Comment by timoschilling** [comment]
@praneetap @sriram-mv any updates on this?

**Comment by timoschilling** [comment]
@praneetap @sriram-mv any updates on this?

**Comment by timoschilling** [comment]
Can we get this merged?

**Comment by ayozemr** [comment]
any updates on this? ty

**Comment by TomBeckett** [comment]
Any updates on this release?

**Comment by boonew2** [comment]
Seems like this work got merged in with https://github.com/aws/serverless-application-model/pull/1725

Any reason this PR should be kept open?

**Pull request closed without merging**
